runtime: custom
api_version: '1.0'
env: flex
service: api-beta
runtime_config:
  jdk: openjdk11
threadsafe: true
resources:
  cpu: 2
  memory_gb: 7.5
  disk_size_gb: 10
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 60 # default value
  cpu_utilization:
    target_utilization: 0.9
liveness_check:
  path: "/api/v4/meta/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 1
readiness_check:
  path: "/api/v4/meta/health"
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 5
  success_threshold: 1
  app_start_timeout_sec: 300
#health_check:
#  enable_health_check: True

